version: "3.11"
services:
  db:
    image: postgres:latest
    container_name: db_app
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
    expose:
      - 5432
    ports:
        - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    image: first_case:0.1
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000;