version: "3.11"
services:
  db:
    image: postgres:latest
    container_name: db_app
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
      
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/app/docker/app.sh"]
volumes:
  data: